In [1]:
import numpy as np
lst1 = [1,2,3]
array1 = np.array(lst1)

In [2]:
lst1

[1, 2, 3]

In [3]:
array1

array([1, 2, 3])

In [4]:
type(lst1)

list

In [5]:
type(array1)

numpy.ndarray

In [6]:
lst2 = [10,11,12]

In [7]:
array2 = np.array(lst2)

In [13]:
print("Adding two lists ",lst1, " and ",lst2, " together: ", lst1+lst2)

Adding two lists  [1, 2, 3]  and  [10, 11, 12]  together:  [1, 2, 3, 10, 11, 12]


In [14]:
print("Adding two numpy arrays ", array1, " and ", array2, " together : ", array1+array2)

Adding two numpy arrays  [1 2 3]  and  [10 11 12]  together :  [11 13 15]


In [16]:
print("array2 multiplied by array1", array1*array2)
print("array2 divided by array1", array2/array1)
print("array2 raised to power array1", array2**array1)

array2 multiplied by array1 [10 22 36]
array2 divided by array1 [10.   5.5  4. ]
array2 raised to power array1 [  10  121 1728]


In [18]:
# Sine function
print("Sine : ", np.sin(array1))

# Logaritm
print("natural logarithm : ", np.log(array1))
print("Base 10 logarithm : ", np.log10(array1))
print("Base 2 logarithm : ", np.log2(array1))

#Exponential
print("Exponential : ", np.exp(array1))

Sine :  [0.84147098 0.90929743 0.14112001]
natural logarithm :  [0.         0.69314718 1.09861229]
Base 10 logarithm :  [0.         0.30103    0.47712125]
Base 2 logarithm :  [0.        1.        1.5849625]
Exponential :  [ 2.71828183  7.3890561  20.08553692]


# Mathematical operations with/on Numpy arrays
### Logarithms
##### (base)pow = number
##### What Power of 2 is 16 ??
##### i.e. log2(16) = ?
##### log2(16) = 4
##### (2)4 = 8
##### log10(10) = 2

##### (2)-3 = 1/8

In [26]:
print(np.log10(100))
np.e

2.0


2.718281828459045

### How to generate arrays easily
* `np.zeroes`
* `np.ones`
* `np.arange`
* `np.linspace`

In [35]:
print("A series of zeroes : ", np.zeros(7))
print("A series of ones : ", np.ones(9))
print("A series of numbers : ", np.arange(5,16))
print("Numbers spaced apart by 2 : ", np.arange (0,11,2))
print("Numbers spaced apart by float: ", np.arange(0,11,2.5))
print("Every 5th number from 30 in reverse order: ", np.arange(30,-1,-5))
print("11 linearly spaced numbers spaced between 1 and 5", np.linspace(1,5,11))

A series of zeroes :  [0. 0. 0. 0. 0. 0. 0.]
A series of ones :  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
A series of numbers :  [ 5  6  7  8  9 10 11 12 13 14 15]
Numbers spaced apart by 2 :  [ 0  2  4  6  8 10]
Numbers spaced apart by float:  [ 0.   2.5  5.   7.5 10. ]
Every 5th number from 30 in reverse order:  [30 25 20 15 10  5  0]
11 linearly spaced numbers spaced between 1 and 5 [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


## Multi-dimensional arrays

In [37]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [38]:
mat = np.array(my_mat)

In [39]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print(type(mat))

<class 'numpy.ndarray'>


In [50]:
my_tuple = np.array([(1.5,2,3), (4,5,6)])
print(type(my_tuple))
mat_tuple = np.array(my_tuple)
print(type(mat_tuple))
print(mat_tuple)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [53]:
print(mat)
print("Dimension of this matrix: ",mat.ndim,sep='') 
print("Size of this matrix: ", mat.size,sep='') 
print("Shape of this matrix: ", mat.shape,sep='')
print("Data type of this matrix: ", mat.dtype,sep='')


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [54]:
print("Vector of zeros: ",np.zeros(5))
print("Matrix of zeros: ",np.zeros((3,4)))
print("Vector of ones: ",np.ones(4))
print("Matrix of ones: ",np.ones((4,2)))
print("Matrix of 5’s: ",5*np.ones((3,3)))
print("Identity matrix of dimension 2:",np.eye(2))
print("Identity matrix of dimension 4:",np.eye(4))
print("Random matrix of shape (4,3):\n",np.random.randint(low=1,high=10,size=(4,3)))

Vector of zeros:  [0. 0. 0. 0. 0.]
Matrix of zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Vector of ones:  [1. 1. 1. 1.]
Matrix of ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5’s:  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Identity matrix of dimension 2: [[1. 0.]
 [0. 1.]]
Identity matrix of dimension 4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix of shape (4,3):
 [[6 7 6]
 [2 9 3]
 [9 5 7]
 [5 7 7]]


In [55]:
a = np.random.randint(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)

In [59]:
print(a)

[36 54 65 95 83 45 54  2 45 23 87 75 99 77 25  2 21 53 73 89 25 63 39 71
  2 30 54 20 43 67]


In [60]:
print(b)

[[[36 54 65 95 83]
  [45 54  2 45 23]
  [87 75 99 77 25]]

 [[ 2 21 53 73 89]
  [25 63 39 71  2]
  [30 54 20 43 67]]]


In [61]:
print(c)

[[36 54 65 95 83]
 [45 54  2 45 23]
 [87 75 99 77 25]
 [ 2 21 53 73 89]
 [25 63 39 71  2]
 [30 54 20 43 67]]


In [62]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [63]:
b_flat = b.ravel()
print(b_flat)

[36 54 65 95 83 45 54  2 45 23 87 75 99 77 25  2 21 53 73 89 25 63 39 71
  2 30 54 20 43 67]


In [64]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr2 = np.arange(0,21,2)
print("New array:",arr2)
print("Elements at 2nd, 4th, and 9th index are:", arr2[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [65]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)

print("\nDouble bracket indexing\n")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
 [[19 98 87 46 21]
 [53 51 19 80 74]
 [81 93 46 72 21]]

Double bracket indexing

Element in row index 1 and column index 2: 19

Single bracket with comma indexing

Element in row index 1 and column index 2: 19

Row or column extract

Entire row at index 2: [81 93 46 72 21]
Entire column at index 3: [46 80 72]

Subsetting sub-matrices

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[80 74]
 [72 21]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[98 46]
 [51 80]]


## Conditional subsetting

In [66]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)
print ("\nElements greater than 50\n", mat[mat>50])

Matrix of random 2-digit numbers
 [[15 35 67 19 26]
 [47 41 46 68 96]
 [13 31 26 53 61]]

Elements greater than 50
 [67 68 96 53 61]


In [67]:
mat>50

array([[False, False,  True, False, False],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True]])

In [68]:
mat*(mat>50)

array([[ 0,  0, 67,  0,  0],
       [ 0,  0,  0, 68, 96],
       [ 0,  0,  0, 53, 61]])

## Array operations (array-array, array-scalar, universal functions)

In [69]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n",mat2)

print("\nAddition\n", mat1+mat2)
print("\nMultiplication\n", mat1*mat2)
print("\nDivision\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
 [[3 6 2]
 [7 7 3]
 [1 7 5]]

2nd Matrix of random single-digit numbers
 [[1 6 8]
 [9 7 6]
 [6 1 3]]

Addition
 [[ 4 12 10]
 [16 14  9]
 [ 7  8  8]]

Multiplication
 [[ 3 36 16]
 [63 49 18]
 [ 6  7 15]]

Division
 [[3.         1.         0.25      ]
 [0.77777778 1.         0.5       ]
 [0.16666667 7.         1.66666667]]

Lineaer combination: 3*A - 2*B
 [[  7   6 -10]
 [  3   7  -3]
 [ -9  19   9]]

Addition of a scalar (100)
 [[103 106 102]
 [107 107 103]
 [101 107 105]]

Exponentiation, matrix cubed here
 [[ 27 216   8]
 [343 343  27]
 [  1 343 125]]

Exponentiation, sq-root using pow function
 [[1.73205081 2.44948974 1.41421356]
 [2.64575131 2.64575131 1.73205081]
 [1.         2.64575131 2.23606798]]


## Pandas series

In [70]:
import pandas as pd

In [71]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'c': 30, 'a': 10, 'b': 20}


In [72]:
s1=pd.Series(data=my_data)
print(s1)

0    10
1    20
2    30
dtype: int64


In [73]:
s2=pd.Series(data=my_data, index=labels)
print(s2)

a    10
b    20
c    30
dtype: int64


In [74]:
s3=pd.Series(arr, labels)
print(s3)

a    10
b    20
c    30
dtype: int64
